# Generated by Django 4.1.4 on 2023-02-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_teacher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='top',
        ),
    ]
