# Generated by Django 4.1.4 on 2023-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_file_alter_category_image_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_en',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='about_ru',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='about_uz',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
