# Generated by Django 4.1.4 on 2023-03-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_course_about_en_course_about_ru_course_about_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
