# Generated by Django 4.1.4 on 2023-04-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_icon', to='academy.file'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_image', to='academy.file'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_uz', models.TextField(blank=True, max_length=200000, null=True)),
                ('about_ru', models.TextField(blank=True, max_length=200000, null=True)),
                ('about_en', models.TextField(blank=True, max_length=200000, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.file')),
            ],
        ),
    ]
